# Generated by Django 3.2.6 on 2021-08-16 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('userPassword', models.CharField(max_length=20)),
                ('accessKey', models.CharField(default='c', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('submittedDate', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statusCheck', models.CharField(blank=True, max_length=200, null=True)),
                ('OAstatus', models.CharField(choices=[('None', 'None'), ('Not Started', 'Not Started'), ('Completed', 'Completed')], default='None', max_length=20)),
                ('OAdue', models.DateTimeField(blank=True, null=True)),
                ('OAlink', models.DateTimeField(blank=True, null=True)),
                ('OAthoughts', models.CharField(choices=[('meh', 'meh'), ('hype', 'hype'), (':(', ':(')], default='meh', max_length=5)),
                ('pending', models.BooleanField(default=True)),
                ('rejected', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('interviewInvite', models.BooleanField(default=False)),
                ('interviewDate', models.DateField(blank=True, null=True)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appleCation.cat')),
            ],
        ),
    ]
