# Generated by Django 3.2.6 on 2021-08-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appleCation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='cat',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='appleCation.cat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='accessKey',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
