# Generated by Django 3.2.6 on 2021-08-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appleCation', '0002_auto_20210816_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appleCation.cat'),
        ),
    ]
