# Generated by Django 3.2.6 on 2021-08-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appleCation', '0003_alter_apple_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='accessKey',
            field=models.CharField(default='c', max_length=200),
        ),
    ]
