# Generated by Django 3.1.4 on 2021-08-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appleCation', '0003_auto_20210817_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appleCation.cat', to_field='accessKey'),
        ),
    ]
